version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  your_app_service:
    # Configuración de tu aplicación
    # Por ejemplo:
    image: appweb
    ports:
      - "3000:3000"
    volumes:
      - ./tu_aplicacion:/app

volumes:
  mongodb_data:
